---
title: "RWorksheet_TIAD#3b"
author: "James Cedrick Tiad"
date: "2024-10-02"
output: pdf_document
---

```{r}
#1.
  #a.
  Respondents <- c(1:20)
  Sex <- c(2,2,1,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,1,2)
  FathersOccupation <- c(1,3,3,3,1,2,3,1,1,1,3,2,1,3,3,1,3,1,2,1)
  Personsathome <- c(5,7,3,8,5,9,6,7,8,4,7,5,4,7,8,8,3,11,7,6)
  Siblingsatschool <- c(6,4,4,1,2,1,5,3,1,2,3,2,5,5,2,1,2,5,3,2)
  Typesofhouses <- c(1, 2, 3, 1, 1, 3, 3, 1, 2, 3, 2, 3, 2, 2, 3, 3, 3, 3, 3, 2)
  
  A_df <- data.frame(Respondents = Respondents, Sex = Sex, FathersOccupation = FathersOccupation, Persons_At_Home = Personsathome, Siblings_At_School = Siblingsatschool, Types_Of_Houses = Typesofhouses)
  A_df
  #b. 
  #The data is displayed using data frame which is very convenient and organized.
  #Here's the structure and summary.
  summary(A_df)
  str(A_df)
  #c.
  mean(A_df[,5])
  #The mean is not 5 instead it is 2.95.
  #d.
  f2rows <- A_df[1:2,]
  f2rows
  #e.
  extract3_5 <- A_df[c(3,5), c(2,4)]
  extract3_5
  #f.
  types_houses <- A_df[,6]
  types_houses
  #g.
  MALE_farm <- subset(A_df, A_df[,2] == 1 & A_df[,3] == 1 )
  MALE_farm
  #h.
  Female_SCHOOL <- subset(A_df, A_df[,2] == 2 & A_df[,5] >= 5)
  Female_SCHOOL
```

```{r}
#2.
   #a.
  df = data.frame(Ints=integer(),

  Doubles=double(), Characters=character(),
  Logicals=logical(),
  Factors=factor(),
  stringsAsFactors=FALSE)

  print("Structure of the empty dataframe:")
  print(str(df))
```

```{r}
#3. Create a .csv file of this. Save it as HouseholdData.csv
respondents <- c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
sex <- c("Male", "Female", "Female", "Male", "Male", "Female", "Female", "Male", "Female", "Male")
father <- c(1, 2, 3, 3, 1, 2, 2, 3, 1, 3)
persons <- c(5, 7, 3, 8, 6, 4, 4, 2, 11, 6)
siblings <- c(2, 3, 0, 5, 2, 3, 1, 2, 6, 2)
houses <- c("Wood", "Congrete", "Congrete", "Wood", "Semi-congrete", "Semi-congrete", "Wood", "Semi-congrete", "Semi-congrete", "Congrete")

HOUSEdata <- data.frame(Respondents = respondents, Sex = sex, fathers_occupation = father, Persons_at_Home = persons, Siblings_at_School = siblings, Types_of_Houses = houses)
HOUSEdata

write.csv(HOUSEdata, file = "HouseholdData.csv", FALSE)
  #a.
 Imported <- read.csv("HouseholdData.csv")
 Imported
 #b.
 HOUSEdata$Sex <- factor(HOUSEdata$Sex, levels = c("Male", "Female"), labels = c(1, 2))
  HOUSEdata
 #c.
 HOUSEdata$Types_of_Houses <- factor(HOUSEdata$Types_of_Houses, levels = c("Wood", "Congrete", "Semi-congrete"), labels = c(1, 2, 3))
HOUSEdata
 #d.
 HOUSEdata$fathers_occupation <- factor(HOUSEdata$fathers_occupation, levels = c(1, 2, 3), labels = c("Farmer","Driver","Other"))
HOUSEdata
 #e.
 FR_drivers <- subset(HOUSEdata, Sex == 2 & fathers_occupation =="Driver")
 print(FR_drivers)
 #f.
 siblings_g5 <- subset(HOUSEdata, Siblings_at_School >= 5)
 siblings_g5
#4.
#The graph highlights how people’s feelings in tweets changed over several days,
#with shifts in positive, neutral, and negative sentiments. Negative tweets 
#peaked on July 15, likely in response to bad news, while there was an increase 
#in positive tweets on July 17, indicating a better mood. By July 20, neutral 
#tweets became the most common, suggesting more balanced or informational 
#posts during that time.
```

