---
title: "RWorkSheet_TIAD#4c"
author: "James Cedrick Tiad"
date: "2024-11-04"
output: pdf_document
---

```{r}
#1.
#a.
mpgfile <- read.csv("D://RScripts//mpg.csv")
mpgfile

#b.
  #The Cathegorical variables would be year, transmission, drv, class, fl
#c.
  #The Continuous variables would be displ
```

```{r}
#2.
mostmanufac_model <- names(which.max(table(mpgfile$manufacturer)))
mostmanufac_model

mostmodel_var <- names(which.max(table(mpgfile$model)))
mostmodel_var

#a.
library(ggplot2)
library(dplyr)
Manu_mdl_cnt <- mpgfile %>%
  group_by(manufacturer) %>%
  summarise(unique_models = n_distinct(model)) %>%
  arrange(desc(unique_models))

Manu_mdl_cnt

#b.
ggplot(Manu_mdl_cnt, aes(x = reorder(manufacturer, -unique_models), y = unique_models)) +
  geom_bar(stat = "identity", fill = "lightblue") +
  labs(title = "Unique Models by Manufacturer", x = "Manufacturer", y = "Count") + theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}
#2

#a
ggplot(mpg, aes(model, manufacturer)) + geom_point()
#It creates a scatter plot where each point represents a specific model-manufacturer combination.

#b
#It is useful but the x-axis have too many categories, making the plot cluttered and unreadable.
```

```{r}
#3
library(ggplot2)
library(dplyr)

top_20_DATA <- mpgfile %>% head(20)

ggplot(top_20_DATA, aes(x = model, y = year)) +
  geom_point() +
  labs(title = "Top 20 Car Models by Year") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
#4
model_cnt <- mpgfile %>%
  group_by(model) %>%
  summarise(car_count = n())

model_cnt

#a
top_20_DATA <- model_cnt %>% top_n(20, car_count)

ggplot(top_20_DATA, aes(x = reorder(model, car_count), y = car_count, fill = model)) +
  geom_bar(stat = "identity") +
  labs(title = "Top 20 Car Models by Count (Flipped)",
       x = "Car Model",
       y = "Count") 

#b
ggplot(top_20_DATA, aes(x = reorder(model, car_count), y = car_count, fill = model)) +
  geom_bar(stat = "identity") +
  labs(title = "Top 20 Car Models by Count",
       x = "Car Model",
       y = "Count") + coord_flip() 
```

```{r}
#5

#a
#I observed that points with higher cylinder counts (cyl) align with higher values of engine displacement (displ).

ggplot(mpgfile, aes(x = cyl, y = displ, color = displ)) +
  geom_point() +
  labs(title = "Relationship between No. of Cylinders and Engine Displacement",
       x = "Number of Cylinders",
       y = "Engine Displacement (L)")
```

```{r}
#6
ggplot(mpgfile, aes(x = displ, y = hwy, color = cyl)) +
  geom_point() +
  labs(title = "Relationship between Engine Displacement and Highway MPG",
       x = "Engine Displacement (L)",
       y = "Highway MPG")
```

```{r}
#6.
traffic_data <- read.csv("D://RScripts//traffic.csv")
traffic_data

#a.
str(traffic_data)
#This dataset has 4 variables which is DataTime, Junction, Vehicles, and ID.

#b.
junction <- subset(traffic_data, select = Junction)
head(junction)
tail(junction)

#c.
library(ggplot2)
ggplot(traffic_data, aes(x = DateTime, y = Vehicles, color = Junction)) +
  geom_line() +
  labs(title = "Traffic Counts by Junction", x = "Date & Time", y = "Vehicles")

```

```{r}
#7.
library("readxl")
alexa_data <- read_xlsx("D://RScripts//alexa_file.xlsx")

#a.
str(alexa_data)
ncol(alexa_data)
#alexa file has 3,150 observations and 5 columns

#b.
library(dplyr)
variation_ttl <- alexa_data %>%
  group_by(variation) %>%
  summarize(total = n())
print(variation_ttl)

#c.
ggplot(variation_ttl, aes(x = variation, y = total, fill = variation)) +
  geom_bar(stat = "identity") +
  labs(title = "Total Variations", x = "Variation", y = "Total") +
  theme_minimal()

#d.
library(dplyr)
num_of_verified_reviews <- alexa_data %>%
  group_by(date) %>%
  summarize(count = n()) %>%
  arrange(date)

library(ggplot2)
ggplot(num_of_verified_reviews, aes(x = date, y = count)) +
  geom_line(color = "blue") +
  labs(title = "Verified Reviews Over Time", x = "Date", y = "Verified Reviews") +
  theme_minimal()

#e.
variation_rate <- alexa_data %>%
  group_by(variation) %>%
  summarize(avg_rating = mean(rating, na.rm = TRUE)) %>%
  arrange(desc(avg_rating))
variation_rate

ggplot(variation_rate, aes(x = reorder(variation, avg_rating), y = avg_rating, fill = variation)) +
  geom_bar(stat = "identity") +
  labs(title = "Average Ratings by Variation", x = "Variation", y = "Average Rating") +
  coord_flip()
```

