---
title: "RWorksheet_Tiad#4a"
author: "James Cedrick Tiad"
date: "2024-10-14"
output: pdf_document
---

```{r}
#1.
  #a. The following table shows Shoe sizes, Height and gender data.
  #b.
  Shoe_size <- c(6.5,9.0,8.5,8.5,10.5,7.0,9.5,9.0,13.0,7.5,10.5,8.5,12.0,10.5,13.0,11.5,8.5,5.0,10.0,6.5,7.5,8.5,10.5,8.5,10.5,11.0,9.0,13.0
)
  Height <- c(66.0,68.0,64.5,65.0,70.0,64.0,70.0,71.0,72.0,64.0,74.5,67.0,71.0,71.0,77.0,72.0,59.0,62.0,72.0,66.0,64.0,67.0,73.0,69.0,72.0,70.0,69.0,70.0)
  Gender <- c("F","F","F","F","M","F","F","F","M","F","M","F","M","M","M","M","F","F","M","F","F","M","M","F","M","M","M","M")
  Shoe_Table <- data.frame(Shoe_size, Height, Gender)
  Shoe_Table
  
  Male_Shoesizes <- subset(Shoe_Table, Gender == "M", select = c(Shoe_size, Height, Gender))
  Male_Shoesizes
  
   Female_Shoesizes <- subset(Shoe_Table, Gender == "F", select = c(Shoe_size, Height, Gender))
  Female_Shoesizes
  
  #c.mean of Shoes sizes  
  mean_sizes <- mean(Shoe_size)
  mean_sizes
  
  #mean of Height
  mean_height <- mean(Height)
  mean_height
  
  #d. Yes I think there is a relationship between Shoe sizes and height. Because                                             the taller you are the bigger your shoe size gets. 
```

```{r}
#2.
  months <- c("March", "April", "January", "November", "January", "September", "October", "September", "November", "August", "January", "November", "November", "February", "May", "August", "July", "December", "August", "August", "September", "November", "February", "April")

  factor_months <- factor(months)
  factor_months
  
  assign("factor_months_vector", factor_months)
  factor_months_vector

#3.
  summary(months)
  
  summary(factor_months_vector)
```

```{r}
#4.
  Direction <- c("East", "West", "North")
  frequency <- c(1,4,3)
  difre_df <- data.frame(Direction,frequency)
  difre_df
  
  new_order_data <- factor(Direction, levels = c("East", "West", "North"))
  new_order_data
```

```{r}
#5.
  #a.
  excel_table <- read.table("import_march.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE)
  excel_table
```

```{r}
#Using Conditional Statement
#6.Full search
  x <- readline(prompt = "Enter a number between 1 to 50: ")
  if(x <= 50 && x >= 1){
    print("TRUE")
    x
   }else{
    print("The number selected is beyond the range of 1 to 50")
   }
```

```{r}
#7. Change
 price_input <- as.numeric(readline(prompt = "Enter the price of the snack (divisible by 50): "))

calculate_minimum_bills <- function(price) {
  if (is.na(price)) {
    cat("Please enter a valid number.\n")
    return()
  }
  
  if (price %% 50 != 0) {
    cat("Price must be a number divisible by 50.\n")
  } else {
    denominations <- c(1000, 500, 200, 100, 50)
    
    bill_count <- 0
    
    for (denom in denominations) {
      if (price >= denom) {
        count <- price %/% denom
        bill_count <- bill_count + count
        price <- price - (count * denom)
      }
    }
    
    if (bill_count > 0) {
      cat("Minimum number of bills needed:", bill_count, "\n")
    } else {
      cat("No bills needed.\n")
    }
  }
}

calculate_minimum_bills(price_input)

```

```{r}
#8.
#a.
Name <- c("Annie", "Thea", "Steve", "Hanna")
Grade1 <- c(85, 65, 75, 95)
Grade2 <- c(65, 75, 55, 75)
Grade3 <- c(85, 90, 80, 100)
Grade4 <- c(100, 90, 85, 90)

Grade_df <- data.frame(Name, Grade1, Grade2, Grade3, Grade4)
Grade_df

#b.
Grade_df$Average <- (Grade_df$Grade1 + Grade_df$Grade2 + Grade_df$Grade3 + Grade_df$Grade4) / 4

for (i in 1:nrow(Grade_df)) {
  if (Grade_df$Average[i] > 90) {
    cat(Grade_df$Name[i], "’s average grade this semester is", round(Grade_df$Average[i], 2), ".\n")
  }
}

#c
test_averages <- numeric(ncol(Grade_df) - 1)

for (j in 2:ncol(Grade_df)) { 
  total_score <- 0
  for (i in 1:nrow(Grade_df)) {
    total_score <- total_score + Grade_df[i, j]
  }
  test_averages[j - 1] <- total_score / nrow(Grade_df)
}

for (n in 1:length(test_averages)) {
  if (test_averages[n] < 80) {
    cat("The", n, "test was difficult.\n")
  }
}

#d.
for (i in 1:nrow(Grade_df)) {
  highest_score <- Grade_df[i, 2]
 
  for (j in 3:ncol(Grade_df)) {  
    if (Grade_df[i, j] > highest_score) {
      highest_score <- Grade_df[i, j]  
    }
  }
  
  
  if (highest_score > 90) {
    cat(Grade_df$Name[i], "’s highest grade this semester is", highest_score, ".\n")
  }
}
```

